# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-18 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20170614_1646'),
        ('samples', '0029_patient_simple_art_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionReasons',
            fields=[
                ('appendix_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Appendix')),
            ],
            bases=('backend.appendix',),
        ),
    ]
