# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-07 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0030_rejectionreasons'),
        ('samples', '0035_sample_sample_medical_lab'),
    ]

    operations = [
    ]
