# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-10 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0036_merge'),
        ('samples', '0039_auto_20171109_1438'),
    ]

    operations = [
    ]
