# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-07-26 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appendix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('appendix', models.CharField(max_length=64)),
                ('tag', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'backend_appendices',
                'verbose_name_plural': 'Appendices',
            },
        ),
        migrations.CreateModel(
            name='AppendixCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'backend_appendix_categories',
                'verbose_name_plural': 'Appendix Categories',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=32, unique=True)),
                ('map_code', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'backend_districts',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=128)),
                ('hub_facility', models.BooleanField(default=False)),
                ('facility_contact', models.CharField(max_length=64)),
                ('facility_email', models.EmailField(max_length=128)),
                ('physical_address', models.CharField(max_length=128)),
                ('return_address', models.CharField(max_length=128)),
                ('coordinator_name', models.CharField(max_length=64)),
                ('coordinator_contact', models.CharField(max_length=64)),
                ('coordinator_email', models.EmailField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.District')),
            ],
            options={
                'db_table': 'backend_facilities',
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub', models.CharField(max_length=32, unique=True)),
                ('hub_email', models.EmailField(max_length=128)),
                ('coordinator_name', models.CharField(max_length=64)),
                ('coordinator_contact', models.CharField(max_length=64)),
                ('coordinator_email', models.EmailField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'backend_hubs',
            },
        ),
        migrations.CreateModel(
            name='HubRider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider', models.CharField(max_length=64)),
                ('contact', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('number_plate', models.CharField(max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Hub')),
            ],
            options={
                'db_table': 'backend_hub_riders',
                'verbose_name_plural': 'Hub Riders',
            },
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=64)),
                ('ip_email', models.EmailField(max_length=128)),
                ('website', models.URLField(max_length=128)),
                ('focal_person_name', models.CharField(max_length=64)),
                ('focal_person_contact', models.CharField(max_length=64)),
                ('focal_person_email', models.EmailField(max_length=128)),
                ('funding_source', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'backend_ips',
            },
        ),
        migrations.CreateModel(
            name='IpFacilitySupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('stopped', models.BooleanField(default=False)),
                ('stop_date', models.DateField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Facility')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Ip')),
            ],
            options={
                'db_table': 'backend_ip_facility_support',
                'verbose_name_plural': 'IP Facility Support',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'backend_regions',
            },
        ),
        migrations.AddField(
            model_name='hub',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Ip'),
        ),
        migrations.AddField(
            model_name='facility',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Hub'),
        ),
        migrations.AddField(
            model_name='facility',
            name='ips',
            field=models.ManyToManyField(through='backend.IpFacilitySupport', to='backend.Ip'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Region'),
        ),
        migrations.AddField(
            model_name='appendix',
            name='appendix_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.AppendixCategory'),
        ),
    ]
