# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-07-18 13:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appendix',
            options={'verbose_name_plural': 'appendices'},
        ),
        migrations.AlterModelOptions(
            name='appendixcategory',
            options={'verbose_name_plural': 'appendix_categories'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': 'districts'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'facilities'},
        ),
        migrations.AlterModelOptions(
            name='hub',
            options={'verbose_name_plural': 'hubs'},
        ),
        migrations.AlterModelOptions(
            name='hubrider',
            options={'verbose_name_plural': 'hub_riders'},
        ),
        migrations.AlterModelOptions(
            name='ip',
            options={'verbose_name_plural': 'ips'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': 'regions'},
        ),
        migrations.AlterField(
            model_name='ipfacilitysupport',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 18, 13, 58, 35, 926418, tzinfo=utc)),
        ),
    ]
