# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-07-18 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20160718_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipfacilitysupport',
            name='start_date',
            field=models.DateField(),
        ),
    ]
