# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-07-18 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20160718_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appendix',
            options={},
        ),
        migrations.AlterModelOptions(
            name='appendixcategory',
            options={'verbose_name_plural': 'Appendix Categories'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hub',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hubrider',
            options={'verbose_name_plural': 'Hub Riders'},
        ),
        migrations.AlterModelOptions(
            name='ip',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ipfacilitysupport',
            options={'verbose_name_plural': 'IP Facility Support'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterModelTable(
            name='appendix',
            table='backend_appendices',
        ),
        migrations.AlterModelTable(
            name='appendixcategory',
            table='backend_appendix_categories',
        ),
        migrations.AlterModelTable(
            name='district',
            table='backend_districts',
        ),
        migrations.AlterModelTable(
            name='facility',
            table='backend_facilities',
        ),
        migrations.AlterModelTable(
            name='hub',
            table='backend_hubs',
        ),
        migrations.AlterModelTable(
            name='hubrider',
            table='backend_hub_riders',
        ),
        migrations.AlterModelTable(
            name='ip',
            table='backend_ips',
        ),
        migrations.AlterModelTable(
            name='ipfacilitysupport',
            table='backend_ip_facility_support',
        ),
        migrations.AlterModelTable(
            name='region',
            table='backend_regions',
        ),
    ]
