# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-10-30 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_delete_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appendix',
            name='appendix',
            field=models.CharField(max_length=128),
        ),
    ]
