# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-06-14 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20161030_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ('facility',), 'verbose_name_plural': 'Facilities'},
        ),
    ]
