# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-07-19 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20160718_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appendix',
            options={'verbose_name_plural': 'Appendices'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
    ]
