# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-11-05 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0005_auto_20170614_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=128)),
                ('contact', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
            ],
            options={
                'db_table': 'backend_medical_labs',
                'verbose_name_plural': 'Medical Labs',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=64)),
                ('signature', models.FileField(upload_to='signatures')),
                ('medical_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.MedicalLab')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backend_user_profiles',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
