# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-07-24 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20160719_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='appendix',
            name='tag',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
