# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-11-13 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20171113_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Ip'),
        ),
    ]
