# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-11-13 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20171113_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='medicallab',
            name='lab_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
