# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-12-26 20:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0010_auto_20171113_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=64)),
                ('section', models.CharField(max_length=64)),
                ('delete_reason', models.CharField(max_length=128)),
                ('data', models.TextField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backend_delete_logs',
                'verbose_name_plural': 'Logs of Deletes',
            },
        ),
    ]
