# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2018-04-19 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_deletelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pending_dispatch', models.PositiveIntegerField(default=0)),
                ('num_dispatched', models.PositiveIntegerField(default=0)),
                ('last_dispatched_at', models.DateTimeField(null=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.Facility')),
            ],
            options={
                'db_table': 'backend_facility_stats',
                'verbose_name_plural': 'Facility Stats',
            },
        ),
    ]
