# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-23 15:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0012_facilitystats'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntryStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.PositiveIntegerField(default=0)),
                ('yesterday', models.PositiveIntegerField(default=0)),
                ('this_week', models.PositiveIntegerField(default=0)),
                ('last_week', models.PositiveIntegerField(default=0)),
                ('this_month', models.PositiveIntegerField(default=0)),
                ('last_month', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backend_data_entry_stats',
                'verbose_name_plural': 'Data Entry Stats',
            },
        ),
    ]
