# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-28 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_dataentrystats'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentrystats',
            name='acc_last_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataentrystats',
            name='acc_last_week',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataentrystats',
            name='acc_this_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataentrystats',
            name='acc_this_week',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataentrystats',
            name='acc_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataentrystats',
            name='acc_yesterday',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
