# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-04 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_performancestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitystats',
            name='oldest_pending_printing',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
