# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-07-26 23:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worksheet_reference_number', models.CharField(max_length=128)),
                ('machine_type', models.CharField(choices=[('A', 'Abott'), ('R', 'Roche')], max_length=1)),
                ('worksheet_type', models.CharField(choices=[('P', 'Plasma'), ('D', 'DBS')], max_length=1)),
                ('sample_prep', models.CharField(max_length=64)),
                ('sample_prep_expiry_date', models.DateField()),
                ('bulk_lysis_buffer', models.CharField(max_length=64)),
                ('bulk_lysis_buffer_expiry_date', models.DateField()),
                ('control', models.CharField(max_length=64)),
                ('control_expiry_date', models.DateField()),
                ('calibrator', models.CharField(max_length=64)),
                ('calibrator_expiry_date', models.DateField()),
                ('include_calibrators', models.BooleanField(default=False)),
                ('amplication_kit', models.CharField(max_length=64)),
                ('amplication_kit_expiry_date', models.DateField()),
                ('assay_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('results_uploaded', models.BooleanField(default=False)),
                ('printed', models.BooleanField(default=False)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_by', to=settings.AUTH_USER_MODEL)),
                ('worksheet_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vl_worksheets',
            },
        ),
        migrations.CreateModel(
            name='WorksheetSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attached_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_by', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Sample')),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheets.Worksheet')),
            ],
            options={
                'db_table': 'vl_worksheet_samples',
            },
        ),
    ]
