# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-07-19 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='worksheetsample',
            table='vl_worksheet_samples',
        ),
    ]
