# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-08-14 20:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksheet',
            old_name='worksheet_type',
            new_name='sample_type',
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='machine_type',
            field=models.CharField(choices=[('A', 'Abbott'), ('R', 'Roche')], max_length=1),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='worksheet_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
