# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-07-19 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0002_auto_20160719_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='results_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='assay_date',
            field=models.DateTimeField(),
        ),
    ]
