# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-08-23 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0011_auto_20160814_2328'),
        ('worksheets', '0002_auto_20160814_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheetsample',
            name='attached_by',
        ),
        migrations.RemoveField(
            model_name='worksheetsample',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='worksheetsample',
            name='worksheet',
        ),
        migrations.AddField(
            model_name='worksheet',
            name='samples',
            field=models.ManyToManyField(to='samples.Sample'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='bulk_lysis_buffer',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='bulk_lysis_buffer_expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='WorksheetSample',
        ),
    ]
