# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-09-12 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0003_auto_20160823_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='amplication_kit',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='amplication_kit_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='bulk_lysis_buffer',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='bulk_lysis_buffer_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='calibrator',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='calibrator_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='control',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='control_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
