# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-05-11 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0004_auto_20160912_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='machine_type',
            field=models.CharField(choices=[('A', 'Abbott'), ('R', 'Roche'), ('C', 'Cobas 8800')], max_length=1),
        ),
    ]
