# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-05-11 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import samples.models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0005_auto_20170511_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentSamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worksheet_sample', models.ForeignKey(on_delete=samples.models.Sample, to='worksheets.Worksheet')),
            ],
            options={
                'db_table': 'vl_instrument_samples',
            },
        ),
    ]
