# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-05-11 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0006_instrumentsamples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentsamples',
            name='worksheet_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheets.Worksheet'),
        ),
    ]
