# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-05-12 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0007_auto_20170511_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentsamples',
            name='worksheet_sample',
        ),
        migrations.RemoveField(
            model_name='worksheet',
            name='samples',
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='sample_prep',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='sample_prep_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='InstrumentSamples',
        ),
    ]
