# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-05-12 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0016_auto_20161030_2221'),
        ('worksheets', '0008_auto_20170512_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksheetSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id', models.CharField(blank=True, max_length=64, null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Sample')),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheets.Worksheet')),
            ],
            options={
                'db_table': 'vl_worksheet_samples',
            },
        ),
        migrations.AddField(
            model_name='worksheet',
            name='samples',
            field=models.ManyToManyField(through='worksheets.WorksheetSample', to='samples.Sample'),
        ),
    ]
