# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-05-24 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0010_auto_20170523_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheet',
            name='results_uploaded',
        ),
        migrations.AddField(
            model_name='worksheet',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[('A', 'Abbott'), ('R', 'Roche CAP/CTM'), ('C', 'Cobas 8800')], default='1'),
        ),
    ]
