# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-05-31 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0011_auto_20170524_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[('A', 'Abbott'), ('R', 'Roche CAP/CTM'), ('C', 'Cobas 8800')], default=1),
        ),
    ]
