# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-07-03 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0012_auto_20170531_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheet',
            name='printed',
        ),
        migrations.AddField(
            model_name='worksheetsample',
            name='has_result',
            field=models.BooleanField(default=False),
        ),
    ]
