# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-07-05 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0013_auto_20170703_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheetsample',
            name='sample_run',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
