# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-11-20 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0017_worksheet_worksheet_medical_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheetsample',
            name='rack_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
