# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-20 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0019_worksheetprinting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='machine_type',
            field=models.CharField(choices=[('A', 'Abbott'), ('R', 'Roche CAP/CTM'), ('C', 'Cobas 8800'), ('H', 'Hologic')], max_length=1),
        ),
    ]
