# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-12 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0020_auto_20190620_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksheetBarCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_prefix', models.CharField(max_length=1)),
                ('batch_counter', models.PositiveSmallIntegerField()),
                ('bar_code_counter', models.PositiveSmallIntegerField(default=1)),
                ('bar_code', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'bar_code_batches',
            },
        ),
    ]
