# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-16 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0021_worksheetbarcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksheetbarcode',
            old_name='batch_prefix',
            new_name='batch_prefix1',
        ),
        migrations.RemoveField(
            model_name='worksheetbarcode',
            name='bar_code',
        ),
        migrations.RemoveField(
            model_name='worksheetbarcode',
            name='batch_counter',
        ),
        migrations.AddField(
            model_name='worksheetbarcode',
            name='batch_prefix2',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worksheetbarcode',
            name='bar_code_counter',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
