# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-07-19 07:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0005_auto_20160719_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRequestForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'vl_forms',
                'verbose_name_plural': 'Forms',
            },
        ),
        migrations.CreateModel(
            name='ClinicalRequestFormsDispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatched_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Facility')),
            ],
            options={
                'db_table': 'vl_forms_dispatch',
                'verbose_name_plural': 'Forms Dispatch',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=128, unique=True)),
                ('art_number', models.CharField(max_length=64)),
                ('other_id', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Missing Gender')], max_length=1)),
                ('dob', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vl_patients',
            },
        ),
        migrations.CreateModel(
            name='PatientPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_unique_id', models.CharField(max_length=128)),
                ('locator_category', models.CharField(choices=[('V', 'V'), ('R', 'R')], max_length=1)),
                ('locator_envelope', models.CharField(max_length=10)),
                ('locator_position', models.CharField(max_length=3)),
                ('vl_sample_id', models.CharField(max_length=128)),
                ('form_number', models.CharField(max_length=64)),
                ('pregnant', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('anc_number', models.CharField(max_length=64)),
                ('breast_feeding', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('active_tb_status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('date_collected', models.DateField()),
                ('treatment_inlast_sixmonths', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('treatment_initiation_date', models.DateField()),
                ('sample_type', models.CharField(choices=[('P', 'Plasma'), ('D', 'DBS')], max_length=1)),
                ('treatment_indication_other', models.CharField(max_length=64)),
                ('routine_monitoring', models.BooleanField(default=False)),
                ('routine_monitoring_last_test_date', models.DateField(default=False)),
                ('routine_monitoring_last_value', models.CharField(max_length=64)),
                ('routine_monitoring_last_sample_type', models.CharField(choices=[('P', 'Plasma'), ('D', 'DBS')], max_length=1)),
                ('repeat_testing', models.BooleanField(default=False)),
                ('repeat_testing_last_test_date', models.DateField(default=False)),
                ('repeat_testing_last_value', models.CharField(max_length=64)),
                ('repeat_testing_last_sample_type', models.CharField(choices=[('P', 'Plasma'), ('D', 'DBS')], max_length=1)),
                ('suspected_treatment_failure', models.BooleanField(default=False)),
                ('suspected_treatment_failure_last_test_date', models.DateField(default=False)),
                ('suspected_treatment_failure_last_value', models.CharField(max_length=64)),
                ('suspected_treatment_failure_last_sample_type', models.CharField(choices=[('P', 'Plasma'), ('D', 'DBS')], max_length=1)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arv_adherence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arv_adherence', to='backend.Appendix')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('current_regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_regimen', to='backend.Appendix')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Facility')),
                ('failure_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_reason', to='backend.Appendix')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Patient')),
                ('tb_treatment_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tb_treatment_phase', to='backend.Appendix')),
                ('treatment_indication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_indication', to='backend.Appendix')),
                ('treatment_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_line', to='backend.Appendix')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
                ('viral_load_testing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viral_load_testing', to='backend.Appendix')),
            ],
            options={
                'db_table': 'vl_samples',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('comments', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rejection_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Appendix')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Sample')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vl_verifications',
            },
        ),
        migrations.CreateModel(
            name='VerificationRejectionReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Appendix')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Sample')),
            ],
        ),
        migrations.AddField(
            model_name='clinicalrequestform',
            name='dispatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.ClinicalRequestFormsDispatch'),
        ),
    ]
