# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-07-19 11:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0002_auto_20160719_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope_number', models.CharField(max_length=10)),
                ('printed', models.BooleanField(default=False)),
                ('print_date', models.DateTimeField()),
                ('dispatched', models.BooleanField(default=False)),
                ('dispatch_date', models.DateTimeField()),
                ('envelope_dispatched_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelope_dispatched_by', to=settings.AUTH_USER_MODEL)),
                ('envelope_printed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelope_printed_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='dispatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='in_worksheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='printed',
            field=models.BooleanField(default=False),
        ),
    ]
