# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-07-23 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_auto_20160719_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrequestform',
            name='received_back',
            field=models.BooleanField(default=False),
        ),
    ]
