# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-07-27 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_auto_20160727_0837'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='envelope',
            table='vl_envelopes',
        ),
        migrations.AlterModelTable(
            name='patientphone',
            table='vl_patient_phones',
        ),
    ]
