# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-07-28 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_auto_20160727_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='locator_envelope',
        ),
        migrations.AddField(
            model_name='sample',
            name='envelope',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='samples.Envelope'),
            preserve_default=False,
        ),
    ]
