# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-07-31 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_auto_20160728_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrejectionreason',
            name='rejection_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Appendix'),
        ),
    ]
