# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-08-11 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_auto_20160809_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrequestformsdispatch',
            name='ref_number',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Missing Gender'), ('L', 'Left Blank')], max_length=1),
        ),
    ]
