# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-08-11 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_auto_20160811_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalrequestform',
            name='dispatch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.ClinicalRequestFormsDispatch'),
        ),
    ]
