# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-08-14 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0010_auto_20160811_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='treatment_initiation_date',
            field=models.DateField(null=True),
        ),
    ]
