# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-09-05 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0011_auto_20160814_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='vl_sample_id',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
