# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-10-04 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0013_auto_20160906_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='repeat_testing_last_sample_type',
            new_name='last_sample_type',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='repeat_testing_last_test_date',
            new_name='last_test_date',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='repeat_testing_last_value',
            new_name='last_value',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='repeat_testing',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='routine_monitoring',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='routine_monitoring_last_sample_type',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='routine_monitoring_last_test_date',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='routine_monitoring_last_value',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='suspected_treatment_failure',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='suspected_treatment_failure_last_sample_type',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='suspected_treatment_failure_last_test_date',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='suspected_treatment_failure_last_value',
        ),
    ]
