# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2016-10-30 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0015_auto_20161030_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='sample',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='samples.Sample'),
        ),
    ]
