# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-05-23 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0016_auto_20161030_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='dispatched',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='printed',
        ),
    ]
