# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-06-16 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0018_auto_20170616_1213'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together=set([('envelope', 'locator_position')]),
        ),
    ]
