# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-06-16 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0019_auto_20170616_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='breast_feeding',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('L', 'Left Blank')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='pregnant',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('L', 'Left Blank')], max_length=1, null=True),
        ),
    ]
