# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-06-17 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0020_auto_20170616_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='other_regimen',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
