# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-06-25 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0022_auto_20170625_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinician',
            name='phone',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='labtech',
            name='phone',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
