# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-06-25 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0023_auto_20170625_1935'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clinician',
            unique_together=set([('facility', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='labtech',
            unique_together=set([('facility', 'name')]),
        ),
    ]
