# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-06-25 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0024_auto_20170625_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinician',
            old_name='name',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='clinician',
            old_name='phone',
            new_name='cphone',
        ),
        migrations.RenameField(
            model_name='labtech',
            old_name='name',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='labtech',
            old_name='phone',
            new_name='lphone',
        ),
        migrations.AlterUniqueTogether(
            name='clinician',
            unique_together=set([('facility', 'cname')]),
        ),
        migrations.AlterUniqueTogether(
            name='labtech',
            unique_together=set([('facility', 'lname')]),
        ),
    ]
