# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-07-06 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0025_auto_20170625_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='art_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
