# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-07-06 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0026_auto_20170706_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinician',
            name='cphone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='labtech',
            name='lphone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
