# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-07-06 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0027_auto_20170706_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='treatment_inlast_sixmonths',
        ),
        migrations.AddField(
            model_name='sample',
            name='treatment_duration',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '6 months -< 1yr'), (2, '1 -< 2yrs'), (3, '2 -< 5yrs'), (4, '>=5 yrs')], null=True),
        ),
    ]
