# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-07-09 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0028_auto_20170706_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='simple_art_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
