# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-11-01 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0030_auto_20171101_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugResistanceResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results_file', models.FileField(upload_to='drug_resistance_results')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('drr_uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drr_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vl_drug_resistance_results',
            },
        ),
        migrations.RenameModel(
            old_name='DrugResistanceTesting',
            new_name='DrugResistanceRequest',
        ),
        migrations.RenameField(
            model_name='pastregimens',
            old_name='dr',
            new_name='drug_resistance_request',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='who_stage',
            new_name='current_who_stage',
        ),
        migrations.AlterModelTable(
            name='pastregimens',
            table='vl_past_regimens',
        ),
        migrations.AddField(
            model_name='drugresistanceresults',
            name='drug_resistance_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.DrugResistanceRequest'),
        ),
    ]
