# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-11-02 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0031_auto_20171101_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugresistancerequest',
            name='patient_on_rifampcin',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
    ]
