# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-11-02 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0032_auto_20171102_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugresistancerequest',
            old_name='patient_on_rifampcin',
            new_name='patient_on_rifampicin',
        ),
    ]
