# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-11-02 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0033_auto_20171102_0149'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drugresistancerequest',
            table='vl_drug_resistance_requests',
        ),
    ]
