# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-11-07 23:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0035_sample_sample_medical_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envelope',
            name='dispatch_date',
        ),
        migrations.RemoveField(
            model_name='envelope',
            name='dispatched',
        ),
        migrations.RemoveField(
            model_name='envelope',
            name='envelope_dispatched_by',
        ),
        migrations.RemoveField(
            model_name='envelope',
            name='envelope_printed_by',
        ),
        migrations.RemoveField(
            model_name='envelope',
            name='print_date',
        ),
        migrations.RemoveField(
            model_name='envelope',
            name='printed',
        ),
        migrations.AddField(
            model_name='envelope',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 7, 23, 4, 59, 72778)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envelope',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'not_verified'), (2, 'verified'), (3, 'in_worksheet')], default=1),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='envelope_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
