# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-11-08 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0036_auto_20171107_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='envelope_number',
            field=models.CharField(max_length=10),
        ),
    ]
