# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-11-09 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0037_auto_20171108_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='sample_type',
            field=models.CharField(choices=[('P', 'Plasma'), ('D', 'DBS')], default='', max_length=1),
        ),
    ]
