# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-11-09 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_medicallab_userprofile'),
        ('samples', '0038_envelope_sample_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='sample_medical_lab',
        ),
        migrations.AddField(
            model_name='envelope',
            name='sample_medical_lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sample_medical_lab', to='backend.MedicalLab'),
        ),
    ]
