# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-11-20 20:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0039_auto_20171109_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedSamplesRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('released', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(null=True)),
                ('comments', models.TextField(null=True)),
                ('printed', models.BooleanField(default=False)),
                ('downloaded', models.BooleanField(default=False)),
                ('print_date', models.DateTimeField(null=True)),
                ('printed_by', models.CharField(max_length=128, null=True)),
                ('reject_released_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reject_released_by', to=settings.AUTH_USER_MODEL)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='samples.Sample')),
            ],
            options={
                'db_table': 'vl_rejected_samples_release',
            },
        ),
    ]
