# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-12-01 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0040_rejectedsamplesrelease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='locator_position',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together=set([('locator_category', 'envelope', 'locator_position')]),
        ),
    ]
