# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-12-02 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0041_auto_20171201_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='simple_art_number',
        ),
        migrations.AlterField(
            model_name='patient',
            name='unique_id',
            field=models.CharField(max_length=128),
        ),
    ]
