# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-12-03 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0042_auto_20171202_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejectedsamplesrelease',
            name='downloaded',
        ),
        migrations.RemoveField(
            model_name='rejectedsamplesrelease',
            name='print_date',
        ),
        migrations.RemoveField(
            model_name='rejectedsamplesrelease',
            name='printed',
        ),
        migrations.RemoveField(
            model_name='rejectedsamplesrelease',
            name='printed_by',
        ),
    ]
