# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-12-05 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0044_auto_20171205_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtech',
            name='other_name',
        ),
    ]
