# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2017-12-11 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0045_remove_labtech_other_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='treatment_duration',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '6 months -< 1yr'), (2, '1 -< 2yrs'), (3, '2 -< 5yrs'), (4, '5yrs and above'), (5, 'Left Blank')], null=True),
        ),
    ]
