# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150901040355 on 2018-06-20 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0046_auto_20171211_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='vl_sample_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
