# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-18 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_facilitystats'),
        ('samples', '0047_auto_20180620_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionReasons',
            fields=[
                ('appendix_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Appendix')),
            ],
            bases=('backend.appendix',),
        ),
    ]
