# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-14 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0048_rejectionreasons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='art_number',
            new_name='hep_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
