# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-28 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0048_rejectionreasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='pat_edits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verification',
            name='sample_edits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
