# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-14 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0049_auto_20180814_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreliminaryFindings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hbeag_results', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Positive'), (2, 'Negative')], null=True)),
                ('hiv_coinfected', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('L', 'Left Blank')], max_length=1, null=True)),
                ('hiv_hcv_coinfected', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('L', 'Left Blank')], max_length=1, null=True)),
                ('hiv_hcv_tb_coinfected', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('L', 'Left Blank')], max_length=1, null=True)),
                ('hep_other_coinfections', models.CharField(max_length=128)),
                ('alt_value_1', models.PositiveIntegerField(blank=True, null=True)),
                ('alt_value_2', models.PositiveIntegerField(blank=True, null=True)),
                ('alt_value_3', models.PositiveIntegerField(blank=True, null=True)),
                ('ast_value_1', models.PositiveIntegerField(blank=True, null=True)),
                ('ast_value_2', models.PositiveIntegerField(blank=True, null=True)),
                ('ast_value_3', models.PositiveIntegerField(blank=True, null=True)),
                ('alt_value_normal_range', models.CharField(max_length=128)),
                ('platelet_count', models.PositiveIntegerField(blank=True, null=True)),
                ('platelet_normal_range', models.CharField(max_length=128)),
                ('fetal_protein_value', models.PositiveIntegerField()),
                ('fetal_protein_value_normal_range', models.CharField(max_length=128)),
                ('ast_plt_ratio_greater_than_2', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('L', 'Left Blank')], max_length=1, null=True)),
                ('serum_creatinine', models.PositiveIntegerField()),
                ('serum_creatinine_normal_range', models.CharField(max_length=128)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Patient')),
            ],
            options={
                'db_table': 'vl_patient_preliminary_findings',
            },
        ),
    ]
