# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-20 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0049_auto_20180928_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='is_study_sample',
            field=models.BooleanField(default=False),
        ),
    ]
