# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-08 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0049_auto_20180928_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='current_regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_regimen', to='backend.Appendix'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='treatment_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_line', to='backend.Appendix'),
        ),
    ]
