# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-14 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0050_preliminaryfindings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='clinician_request_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 8, 14, 21, 8, 23, 30000)),
            preserve_default=False,
        ),
    ]
