# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-22 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0050_sample_is_study_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='parent_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='parent_id2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
