# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-05 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0050_auto_20190208_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='is_study_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='current_regimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_regimen', to='backend.Appendix'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='treatment_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_line', to='backend.Appendix'),
        ),
    ]
