# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-20 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0050_auto_20190208_1644'),
        ('samples', '0050_sample_is_study_sample'),
    ]

    operations = [
    ]
