# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-10 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0051_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUsedBarcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=128)),
                ('barcode', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'temp_used_barcodes',
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='barcode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
