# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-15 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0051_sample_clinician_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='clinician_request_date',
            field=models.DateField(null=True),
        ),
    ]
