# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-15 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0052_auto_20180815_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliminaryfindings',
            name='ast_value_normal_range',
            field=models.CharField(default=2, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preliminaryfindings',
            name='prem_other_findings',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
