# Generated by Django 3.2.17 on 2023-05-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0051_auto_20190405_1148'),
        ('samples', '0051_auto_20190822_0953'),
        ('samples', '0052_auto_20191010_2034'),
    ]

    operations = [
    ]
