# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-15 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0053_auto_20180815_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='current_drug_name',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Tenofovir'), (2, 'Entecavir')], null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='is_patient_on_treatment',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('L', 'Left Blank')], max_length=1, null=True),
        ),
    ]
