# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-16 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0054_auto_20180815_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='reason_for_vl',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Routing Monitoring'), (2, 'Treatment Initiation')], null=True),
        ),
    ]
