# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-16 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0055_sample_reason_for_vl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='treatment_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_line', to='backend.Appendix'),
        ),
    ]
