# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-16 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0056_auto_20180816_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='viral_load_testing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viral_load_testing', to='backend.Appendix'),
        ),
    ]
