# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-18 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0057_auto_20180816_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preliminaryfindings',
            name='hep_other_coinfections',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='preliminaryfindings',
            name='prem_other_findings',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
