# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-28 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_facilitystats'),
        ('samples', '0058_auto_20180818_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTreatmentIndication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Patient')),
                ('treatment_indication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_indication', to='backend.Appendix')),
            ],
            options={
                'db_table': 'vl_patient_treatment_indication',
            },
        ),
        migrations.RemoveField(
            model_name='sample',
            name='treatment_indication',
        ),
        migrations.AlterField(
            model_name='preliminaryfindings',
            name='fetal_protein_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preliminaryfindings',
            name='fetal_protein_value_normal_range',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='preliminaryfindings',
            name='serum_creatinine',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preliminaryfindings',
            name='serum_creatinine_normal_range',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
