# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-28 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_facilitystats'),
        ('samples', '0060_auto_20180828_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='hiv_current_regimen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiv_current_regimen', to='backend.Appendix'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='current_regimen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_regimen', to='backend.Appendix'),
        ),
    ]
