# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-28 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0061_auto_20180828_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='hiv_current_regimen',
        ),
        migrations.AlterField(
            model_name='sample',
            name='current_regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_regimen', to='backend.Appendix'),
        ),
    ]
