# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-04 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0062_auto_20180828_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='is_study_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preliminaryfindings',
            name='alt_value_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='preliminaryfindings',
            name='alt_value_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='preliminaryfindings',
            name='alt_value_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='preliminaryfindings',
            name='alt_value_normal_range',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='preliminaryfindings',
            name='ast_value_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='preliminaryfindings',
            name='ast_value_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='preliminaryfindings',
            name='ast_value_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='preliminaryfindings',
            name='ast_value_normal_range',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='preliminaryfindings',
            name='fetal_protein_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='preliminaryfindings',
            name='platelet_count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='preliminaryfindings',
            name='platelet_normal_range',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='preliminaryfindings',
            name='serum_creatinine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
